In [4]:
import numpy as np

import torch

inputs = np.array([[30, 70, 12],
                  [60, 110, 5],
                  [40, 20, 11],
                  [50, 50, 3],
                  [45, 30, 11]], dtype = 'float32')

target_cr_scores = np.array([[900],
                   [550],
                   [700],
                   [350],
                   [600]], dtype = 'float32')

inputs = torch.from_numpy(inputs)
target_cr_scores = torch.from_numpy(target_cr_scores)

print(inputs)
print(target_cr_scores)

w = torch.randn(1,3,requires_grad = True)
b = torch.randn(1, requires_grad = True)

print(w)
print(b)

def model(x):
    return x@w.t() + b

predicted_cr_scores = model(inputs)

print(predicted_cr_scores)

print(target_cr_scores)

def mse(t1,t2):
    diff = t1 - t2
    return torch.sum(diff*diff) / diff.numel()

loss = mse(predicted_cr_scores, target_cr_scores)
print(loss)

loss.backward()

with torch.no_grad():
    w-=w.grad * 1e-5
    b-=b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

predicted_cr_scores = model(inputs)
loss = mse(predicted_cr_scores, target_cr_scores)
print(loss)

for i in range (1500000):
    predicted_cr_scores = model(inputs)
    loss = mse(predicted_cr_scores, target_cr_scores)
    loss.backward()
    with torch.no_grad():
        w-=w.grad * 1e-5
        b-=b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

print(predicted_cr_scores)

print(target_cr_scores)
print(w)
print(b)



tensor([[ 30.,  70.,  12.],
        [ 60., 110.,   5.],
        [ 40.,  20.,  11.],
        [ 50.,  50.,   3.],
        [ 45.,  30.,  11.]])
tensor([[900.],
        [550.],
        [700.],
        [350.],
        [600.]])
tensor([[-0.5885, -0.7178, -0.2378]], requires_grad=True)
tensor([1.2357], requires_grad=True)
tensor([[ -69.5175],
        [-114.2196],
        [ -39.2760],
        [ -64.7923],
        [ -49.3964]], grad_fn=<AddBackward0>)
tensor([[900.],
        [550.],
        [700.],
        [350.],
        [600.]])
tensor(504289.8125, grad_fn=<DivBackward0>)
tensor(411917.5000, grad_fn=<DivBackward0>)
tensor([[876.8881],
        [571.7770],
        [653.5157],
        [309.2716],
        [672.9498]], grad_fn=<AddBackward0>)
tensor([[900.],
        [550.],
        [700.],
        [350.],
        [600.]])
tensor([[-2.1301,  3.0084, 51.6496]], requires_grad=True)
tensor([110.4036], requires_grad=True)
